# Generated by Django 3.0.5 on 2021-12-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=900, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('notification', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=1200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('users', models.ManyToManyField(related_name='userevents', to='alertsystem.EventUsers')),
            ],
        ),
    ]
